# Generated by Django 4.1.3 on 2022-11-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('Student_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100)),
                ('university', models.CharField(blank=True, max_length=1000)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('cgpa', models.FloatField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
