# Generated by Django 4.1.3 on 2022-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0002_alter_studentdata_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='mobile',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
