# Generated by Django 4.1.3 on 2022-12-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0003_alter_studentdata_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='student_email_address',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='UniversityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.studentdata')),
            ],
        ),
    ]
