# Generated by Django 4.1.3 on 2022-12-01 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0004_studentdata_student_email_address_universitydata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ielts', models.CharField(max_length=1000)),
                ('toefl', models.CharField(max_length=1000)),
                ('duolingo', models.CharField(max_length=1000)),
                ('pte', models.CharField(max_length=1000)),
                ('others', models.CharField(max_length=1000)),
                ('level_of_education', models.CharField(max_length=1000)),
                ('institute_name', models.CharField(max_length=1000)),
                ('country_of_education', models.CharField(max_length=1000)),
                ('course_studied', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('post_level_of_educaion', models.CharField(max_length=1000)),
                ('post_institute_name', models.CharField(max_length=1000)),
                ('post_country_of_education', models.CharField(max_length=1000)),
                ('post_course_studied', models.CharField(max_length=1000)),
                ('post_start_date', models.DateField()),
                ('post_end_date', models.DateField()),
                ('academic_miscoduct', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('behaviour_misconduct', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('crimal_preceeding', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')])),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='StudenDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.BooleanField(choices=[('Male', 'Male'), ('Female', 'Female')])),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('country_of_birth', models.CharField(max_length=100)),
                ('city_of_birth', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postalcode', models.CharField(max_length=100)),
                ('mailing_address_line_1', models.CharField(max_length=100)),
                ('mailing_address_line_2', models.CharField(max_length=100)),
                ('mailing_address_city', models.CharField(max_length=100)),
                ('mailing_address_state', models.CharField(max_length=100)),
                ('mailing_address_postal_code', models.CharField(max_length=100)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_data', models.CharField(default='', max_length=100)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.studentdata')),
            ],
        ),
        migrations.DeleteModel(
            name='UniversityData',
        ),
    ]
