# Generated by Django 4.1.3 on 2022-12-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0005_educationdetail_studendetail_universitydetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='university',
        ),
    ]
